#!/bin/bash
echo "=== CSV Support Demo Commands ==="
echo ""
echo "Test files created:"
ls -lh test_*.csv
echo ""
echo "=== Quick Start Commands ==="
echo ""
echo "1. Basic CSV viewing:"
echo "   ./dv.py test_tasks.csv"
echo ""
echo "2. CSV with custom delimiter (semicolon):"
echo "   ./dv.py --delimiter ';' test_semicolon.csv"
echo ""
echo "3. CSV without headers:"
echo "   ./dv.py --skip-headers test_no_headers.csv"
echo ""
echo "4. Filter columns:"
echo "   ./dv.py --columns 'name,status' test_tasks.csv"
echo ""
echo "5. Single-select mode (for scripting):"
echo "   ./dv.py -s test_tasks.csv"
echo ""
echo "6. Multiple CSV files as tabs:"
echo "   ./dv.py test_tasks.csv test_mixed.csv"
echo ""
echo "7. Custom tab name:"
echo "   ./dv.py --tab-name 'My Data' test_tasks.csv"
echo ""
echo "=== Try one now ==="
echo ""
read -p "Press Enter to open test_tasks.csv, or Ctrl+C to cancel..."
./dv.py test_tasks.csv
